### ISSUE TITLE
New/First Shipping Option Display Issue

### ISSUE THREAD

**Issue by sklabbers** [elasticpath/react-pwa-reference-storefront#101]
### Step 2: Describe your environment

  
  * Device: laptop & iPhone (PWA)
  * OS version: Window & iOS
  * Storefront pulled version: _____
  * Node version: _____
  * Docker version: _____
  * Docker Compose version: _____

### Step 3: Describe the problem:

When the first/new shipping method is added for a region, it seems that the checkout page goes blank. Selecting the new shipping method once via Studio will subsequently work in the reference store.

I think the underlying issue is that in those cases there is an option, but no options are selected. After selecting it, it becomes the default. 

#### Steps to reproduce:

1. Create a store with no shipping methods.
2. Add a product to the cart, login as a user with an address
3. Go to checkout page
4. In Commerce Manager, add a shipping service level for the region the address is in
5. Go to the checkout page again

Work around:
6. In Cortex studio, go to the defaultorder for the user
7. slect the shipping method in Studio
8. Go to the checkout page again.

#### Observed Results:

Step 3 shows the checkout flow, no shipping options available
Step 5 shows a completely blank screen
Step 8 shows the checkout flow, with a selected  shipping option.

**Comment by shaunmaharaj** [comment]
Fixed additional scenarios where shipping addresses may be unavailable.
