### ISSUE TITLE
Enable Gzip Compression

### ISSUE THREAD

**Issue by kvanderhoek** [elasticpath/react-pwa-reference-storefront#137]
Environment: 
Production: https://reference.elasticpath.com/ + Test browsers provided by Webpage Test and Google Page Speed.

Problem:
According to Webpage Test and Google Page Speed compression is not enabled on https://reference.elasticpath.com/

Steps to Reproduce:
1. Navigate to https://www.webpagetest.org or https://developers.google.com/speed/pagespeed/insights/
2. Type in our production URL: https://reference.elasticpath.com/

Observed Results:
Webpage Test
Use gzip compression for transferring compressable responses: 23/100
1,051.1 KB total in compressible text, target size = 240.9 KB - potential savings = 810.2 KB

FAILED - (551.7 KB, compressed = 147.8 KB - savings of 403.8 KB) - https://reference.elasticpath.com/vendors~app.js
FAILED - (409.6 KB, compressed = 62.4 KB - savings of 347.2 KB) - https://reference.elasticpath.com/app.js
FAILED - (28.3 KB, compressed = 2.0 KB - savings of 26.3 KB) - https://reference.elasticpath.com/cortex/?zoom=navigations:element,navigations:element:child
FAILED - (28.3 KB, compressed = 2.0 KB - savings of 26.3 KB) - https://reference.elasticpath.com/cortex/?zoom=navigations:element,navigations:element:child
FAILED - (6.0 KB, compressed = 2.2 KB - savings of 3.9 KB) - https://reference.elasticpath.com/
FAILED - (1.8 KB, compressed = 0.4 KB - savings of 1.4 KB) - https://reference.elasticpath.com/cortex/?zoom=lookups:navigationlookupform
FAILED - (1.8 KB, compressed = 0.4 KB - savings of 1.4 KB) - https://reference.elasticpath.com/cortex/?zoom=lookups:purchaselookupform

Google Page Speed:
Google Page Speed: 
Text-based resources should be served with compression (gzip, deflate or brotli) to minimize total network bytes. Learn more. 
URL 
Size (KB) 
Potential Savings (KB) 
/vendors~app.js(reference.elasticpath.com) 
552 KB 
404 KB 
/app.js(reference.elasticpath.com) 
410 KB 
347 KB 
/cortex/?zoom=navigations:element,navigations:element:child(reference.elasticpath.com) 
28 KB 
26 KB 
https://reference.elasticpath.com 
6 KB 
4 KB 
/cortex/?zoom=lookups:navigationlookupform(reference.elasticpath.com) 
2 KB 
1 KB 
/cortex/?zoom=lookups:purchaselookupform(reference.elasticpath.com) 
2 KB 
1 KB 

Expected Results:
None of the above failed tests

**Comment by shaunmaharaj** [comment]
@kvanderhoek Thank you for reporting this! We had gzip compression on webpack configured but needed to re-add the same necessary capabilities for nginx.

I've added them in this PR #138.
