### ISSUE TITLE
Duplicate download of key image files

### ISSUE THREAD

**Issue by kvanderhoek** [elasticpath/react-pwa-reference-storefront#142]
### Step 2: Describe your environment
https://reference.elasticpath.com/
Webpage Test: https://www.webpagetest.org or any browser if you clear full browsing history and cached files.

### Step 3: Describe the problem:
We download the following files twice.  Once from s3 and once from https://reference.elasticpath.com/ 
- Company-Logo-v1.png
- homepage-banner.jpg
- brake-icon.jpg
- charging-icon.jpg
- warranty-graphic.jpg

#### Steps to reproduce:
Navigate to https://reference.elasticpath.com/ with dev tools open

#### Observed Results:
You see the above files being downloaded from s3 and then from https://reference.elasticpath.com/.

#### Expected Results:
They should only be downloaded once from 1 location

**Comment by shaunmaharaj** [comment]
Fixed in latest storefront revision.
