### ISSUE TITLE
Numberous Splash screens downloaded for iOS devices

### ISSUE THREAD

**Issue by kvanderhoek** [elasticpath/react-pwa-reference-storefront#147]
### Step 2: Describe your environment
https://reference.elasticpath.com/
Any browser that has had it's cache cleared

### Step 3: Describe the problem:
There appear to be numerous splash screens and icons downloaded if browser cache has been cleared.  The splash screen aren't visible (at least I can't see them and do we really need 4 icon sizes).  Also can we sprite some of these images to reduce round trips?  Would GIF's be better as they appear to be 2 tone images?

Icons:
  - https://reference.elasticpath.com/assets/icons/icon_96x96.96e89d73d9f180d508b65937e5eaacee.png
  - https://reference.elasticpath.com/assets/icons/icon_256x256.b8737e0360bf51d25e45dc8d891dc033.png
  - https://reference.elasticpath.com/assets/icons/icon_512x512.f8980e211966686890d5acf38d4f0ed1.png
  - https://reference.elasticpath.com/images/e090eb08fe409c1a4bfb3fa688af4b43-icons-192.png
  - https://reference.elasticpath.com/assets/icons/icon_128x128.0e13534aedef69f0aa5f98550452acc7.png
  - https://reference.elasticpath.com/images/a924595f85a0f27ce58c0533e435125e-icons-512.png

Splash screens
  - https://reference.elasticpath.com/images/970cfa85588d72a3b1f123b7131ac119-iphonex_splash.png
  - https://reference.elasticpath.com/images/60678b1285ab940fb105795cb6306c57-iphonexr_splash.png
  - https://reference.elasticpath.com/images/59f6626d918035338595b0947e50d5a4-iphone6_splash.png
  - https://reference.elasticpath.com/images/ecf8a674c2618710db6c1ca8543e1e59-ipadpro2_splash.png
  - https://reference.elasticpath.com/images/63d50a18d6e38bf5ff7517a5d9bf8422-iphoneplus_splash.png
  - https://reference.elasticpath.com/images/a91b3dedeb030b27aa0ce9f38cf4334b-ipadpro1_splash.png
  - https://reference.elasticpath.com/images/6e51084591ff128985cd0141b4a85514-iphone5_splash.png
  - https://reference.elasticpath.com/images/02bd38d45eaeffb28f7ace1174f527b3-iphonexsmax_splash.png
  - https://reference.elasticpath.com/images/d19b430145e3a416b06d8901a7b49925-ipad_splash.png
 - 
#### Steps to reproduce:

  1. Clear your browser cache
  2. Close and re-open browser
  3. Open dev tools
  4. Navigate to https://reference.elasticpath.com/
  5. See all the calls for icons and splash screens

#### Observed Results:

Lot's of calls to big files.  Splash screens not visible on the site

#### Expected Results:

Are these necessary? Can they be optimized?

**Comment by petro97** [comment]
After research, there wasn't found ways to optimize this. We’ll keep an eye on it in the ticket.

**Comment by shaunmaharaj** [comment]
Thanks @petro97. We'll keep monitoring this one for the future if there's anything else we can improve on.
