### ISSUE TITLE
Index.html fetched twice on clean cache

### ISSUE THREAD

**Issue by kvanderhoek** [elasticpath/react-pwa-reference-storefront#148]
### Step 2: Describe your environment
https://reference.elasticpath.com/
Any browser that has had it's cache cleared

### Step 3: Describe the problem:
We fetch the index.html twice on the homepage if the browser has a clean cache.

#### Steps to reproduce:

  1. Clear your browser cache
  2. Close and re-open browser
  3. Open dev tools
  4. Navigate to https://reference.elasticpath.com/
  5. See the duplicate calls for index.html

#### Observed Results:
2 calls to fetch https://reference.elasticpath.com/index.html

#### Expected Results:
1 call to fetch https://reference.elasticpath.com/index.html

**Comment by shaunmaharaj** [comment]
Fixed in latest storefront revision.
