### ISSUE TITLE
Use Cloudfront vs. S3 to server image content

### ISSUE THREAD

**Issue by kvanderhoek** [elasticpath/react-pwa-reference-storefront#154]
### Step 2: Describe your environment
https://reference.elasticpath.com/ and http://epstorefront.net/
Any browser

### Step 3: Describe the problem:
Images are currently being served from a combination of the site URL and S3.  For best performance we should be serving these images from a CDN such as Cloudfront.

#### Steps to reproduce:

  1. Clear browser cache and open dev tools
  2. Navigate to Storefront homepage URL
  3. Notice that images are served from a combination of s3 and web server with long initial connection and SSL negotiation times for S3.

#### Observed Results:

Images are served from a combination of s3 and web server with long initial connection and SSL negotiation times for S3.

#### Expected Results:

Images should be server from CDN such as Cloudfront with shorter initial connection and SSL negotiation times

![screen shot 2018-12-13 at 10 18 01 am](https://user-images.githubusercontent.com/4307769/49958714-78e13080-fec0-11e8-9cbd-bc40be4f8b0d.png)

**Comment by shaunmaharaj** [comment]
All remaining demo images have been uploaded to S3 and are served as requested. Icons and splash-screens will continue to be served through the webapp via the manifest.
