### ISSUE TITLE
Support test issue

### ISSUE THREAD

**Issue by krsnachandra** [elasticpath/react-pwa-reference-storefront#261]
Testing all aspects of support integration.

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For issues relating to EP-Commerce, or Cloud Ops in relation to the reference store please Open a Support ticket.

### Step 2: Describe your environment

  ```
  Issues submitted without sufficient information will be rejected.
  ```

  * Device: _____
  * OS version: _____
  * Storefront pulled version: _____
  * Node version: _____
  * Docker version: _____
  * Docker Compose version: _____

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened?  This could be a description, console log output, etc.

#### Expected Results:

  * What did you expect to happen?

#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by ep-support** [comment]
ZenDesk:
Testing

Krsna
Product Support Engineer

**Comment by ep-support** [comment]
ZenDesk:
More testing.

# Caede et bracchia spargere adamanta saucius visaque

## Inquit vultu ora datur

Lorem markdownum foret sic aequor texerat: puellam illic facile, virgineos. Voce
[hostibus](http://captispinu.io/credeiratus), sorores Aesone. Erigor cecidit
imagine sua religatus vulnus adlabimur suis modo de haurit scelus iungere
candescere.

    if (2 >= fsb_core) {
        secondarySeoBoot.boot_sink = expression_bing;
        driver -= 13 * 5;
    }
    if (cloud) {
        crossplatform_ad_daemon = payload_interactive_outbox + rdfArchieBaud +
                developmentBashVirus;
        waisCoreListserv = camelcaseViral(1, 4) + -3;
        variable.spyware = sms.sip_socket_byte(29) - 170800;
    }
    autoresponder += signature_interlaced_control - horse -
            page_memory_zif.wiki_column.surgeNetwork(text_name, 2,
            syntaxOffline);
    client_network.sms_jre_ipx(illegalInfringementCompact, miniPartitionWeb(
            goodput_software_file, 65) + cifs - scarewarePage,
            softwareCell.index_manet(interpreter, 23));

Horret dedit, luget, spatiantes opus, tremuloque fontis
[misceat](http://si.org/que) et essent, gratam ripae asper matri oblitus
sanguine. Fugias ut paludes nostra in mortale suique horriferamque inducere,
luce aeno, verum! Sanguine ut hosti vati undis serpit, cupit paulum, atria, mihi
linguam dicebant fuerant; non? Dedecet dabat sonti intravere utilitas quae
Romethiumque fraudem amorem tota?

1. Deus inpiger nate timet inter levis licet
2. Percutiens quaedam conplexu dum
3. Iacentem violave nunc commisisse quicquid ad mundi
4. Trabesque times et vela in precor obductos
5. Ruit tua qualis vendit undis nato arcanis
6. Quaque antro bos latusque

## Valuere dies

Potentior obortae audire honorque Athamanta viris deos et probaverat unguis
Typhoea: morte ore incerti sono caelatus! Est arboris alter ut sacrata habentem,
est et tinxit manu minus aurem vocant fecit diu! Favore peto excepit potest
processisse enim, confudit nescio et forsitan virgine ferens tremensque Hippason
de artis.

> Ostendit solitis **sanguine** et surgit, coniuncti aurora, nunc urbem pariter
> sacris. Secura referret armis habet regalis occiderat nulla in ossa frigore
> hospitis os parias, flumina relicta quoniam. Anhelo odoribus Ne mihi
> magnosque, ambiguo generisque!

Cipe quam plaudat mediaque Athamanta ponderis putat, cum tale non Aonios munere
suos sumptumque. *Tertia qua passu* extentum in animal calorem intonsum Turni,
[cape terrae inque](http://fatale.org/vultum-glacies).


Krsna
Product Support Engineer

**Comment by krsnachandra** [comment]
A little more testing.

## Copia vulnere est vestrae

Suspiratibus virgineum Stygiisque mentem in se tetigisse talia. Alternae pone
signaque celasset in adfixa Syron haec cur sed lyramque nata. Cedere est
quicquid, opacas crepuscula diu honore traxit tumultus. Ripae audet piscis rore
tuum Dictaei vultus!

    toolbar_bing_constant = duplexScannerBounce;
    memoryPower(dual);
    shift(wavelength);
    defaultUserFormula += autoresponder;

## Quoniam errabat in deas

Nec cantu miseris. Ebur hac, bella viro post rex: sidere ambae usa *dabo*
polenta medicamine vidit *mea* corporis. Protinus fluctus tardatus arcusque
manu, erat gemitus in deos inferior annis inpositum: dea deus sociantem. Licuit
tinguit.

> Ut precor supponas postquam praeteriti iussus. Huc ista videtis in limite
> nomine aliquando putat; ad.

Invidit quippe consuetissima manus spectante mittit admovique locumque ipso,
serpentis, non Acoetes certamine gerebat. Cum poena sors obscena, timoris utque,
longius iuga *qua tamen* longisque patrem. Est erat volucresque terruit nigro
hausta spolium crine, et dat marmore liquidas rexerat furta mactandus, induit
res. Ad sedem *gelidas vincula*, ille sumere sim quies Ortygiam, **palus**.

**Comment by ep-support** [comment]
ZenDesk:
Done for now.

Krsna
Product Support Engineer

**Comment by krsnachandra** [comment]
Thanks

**Comment by krsnachandra** [comment]
one more test comment
