### ISSUE TITLE
Faceted search fails with some valid scopes

### ISSUE THREAD

**Issue by maennis-ep** [elasticpath/react-pwa-reference-storefront#268]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For issues relating to EP-Commerce, or Cloud Ops in relation to the reference store please Open a Support ticket.

### Step 2: Describe your environment

  ```
  Issues submitted without sufficient information will be rejected.
  ```

  * Device: Lenovo Thinkpad
  * OS version: Microsoft Windows 10 Pro v10.0.15063
  * Storefront pulled version: commit 820570cb9aa02cb4fed2b959cabc79478055cb2b
  * Node version: 10.14.2
  * Docker version: n/a
  * Docker Compose version: n/a

### Step 3: Describe the problem:

  Faceted search fails to return results unless the scope in `ep.config.json` is entirely lowercase.  I will submit a PR to address this.

#### Steps to reproduce:

  1. In `ep.config.json`, change the scope from `vestri` to `VESTRI`
  2. Run `npm start`
  3. Search for tires
  4. Select any facet value

#### Observed Results:

  No products are found.  There is a case sensitive string comparison in `CortexLookup.js` looking for scope in a URI.  In Cortex, scope is not a case sensitive value, and the URIs that contain the scope will always be lower case.

#### Expected Results:

  Faceted search to work with any valid scope.

#### Relevant Code:

 n/a

**Comment by krsnachandra** [comment]
Testing an integration.
