### ISSUE TITLE
Buy it again modal styling

### ISSUE THREAD

**Issue by aChanEP** [elasticpath/react-pwa-reference-storefront#276]
* Device: Chrome
  * OS version: MACOS 10.13.3
  * Storefront pulled version:  047526ae732ba6a9cd2e154461d326a60fafe67f
  * Node version: v11.5.0
  * Docker version: NA
  * Docker Compose version: NA

### Step 3: Describe the problem:

![Screen Shot 2019-03-29 at 3 42 19 PM](https://user-images.githubusercontent.com/25829859/55266348-c0a28280-5239-11e9-9a1c-52930b938b18.png)

#### Steps to reproduce:

  1. Head to Buy-it-again option in the order details page
  2. Click to open modal

#### Observed Results:

  Styling is not aligned for item within buy again modal

#### Expected Results:

Items to be aligned in the modal

**Comment by shaunmaharaj** [comment]
Resolved in latest
