### ISSUE TITLE
storybook build errors

### ISSUE THREAD

**Issue by aChanEP** [elasticpath/react-pwa-reference-storefront#336]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For issues relating to EP-Commerce, or Cloud Ops in relation to the reference store please Open a Support ticket.

### Step 2: Describe your environment

  ```
  Issues submitted without sufficient information will be rejected.
  ```

  * Device: MacOS
  * OS version: 10.14.5
  * Storefront pulled version: 52f979f4fb64cc11f390f07463ef71d0b8aa59d4
  * Node version: v11.13.0
  * Docker version: _____
  * Docker Compose version: _____

### Step 3: Describe the problem:
Storybook does not compile and build.
#### Steps to reproduce:

  1. Start the storybook project with `cd storybook && yarn storybook`
  2. Notice the build errors (attached)

#### Observed Results:

<img width="1071" alt="Screen Shot 2019-07-08 at 9 49 48 AM" src="https://user-images.githubusercontent.com/25829859/60828622-b6aceb80-a167-11e9-9631-cf4c11a258a4.png">

#### Expected Results:

  * Expected application to build

#### Relevant Code:

`indirecommendations.main.tsx`

**Comment by shaunmaharaj** [comment]
Hi @aChanEP, thanks for reporting. I'll send you a patch to try and push a fix this afternoon.
