### ISSUE TITLE
No visual feedback when removing Voucher on order or order confirmation.

### ISSUE THREAD

**Issue by sklabbers** [elasticpath/react-pwa-reference-storefront#424]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For issues relating to EP-Commerce, or Cloud Ops in relation to the reference store please Open a Support ticket.

### Step 2: Describe your environment

  * Device: Windows Laptop
  * OS version: Windows 10 Pro v1903
  * Storefront pulled version: (Demo Team)
  * Node version: (Demo Team)
  * Docker version: (Demo Team)
  * Docker Compose version: (Demo Team)

### Step 3: Describe the problem:

The button to remove voucher codes on the order and order confirmation page do seem to remove the voucher, but not update the screen. So if someone where to press that button, they so no changes, however their voucher code is removed, the total price potentially goes up because of this. When pressing complete order, this customer could be paying more than shown on their screen.

#### Steps to reproduce:

  1. Add a voucher to a cart
  2. Proceed to the order screen
  3. Remove voucher
  4. Return to cart
  5. Proceed to order confirmation screen
  6. Remove voucher

#### Observed Results:

  3. No refresh or price updates are done
  4. The voucher has at this stage been removed
  6. No refresh or price updates are done

#### Expected Results:

I expect the screen to update the voucher status, price and discounts at step 4 and 6.

#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by maennis-ep** [comment]
There is a similar issue on the OrderReviewPage.  The onChange function is only being set on the CartPage for the CheckoutSummaryList component.  I am putting together a PR with the fix for this.
