### ISSUE TITLE
Cannot add items with Cart Item Modifiers to multi cart

### ISSUE THREAD

**Issue by mwan-ep** [elasticpath/react-pwa-reference-storefront#517]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For issues relating to EP-Commerce, or Cloud Ops in relation to the reference store please Open a Support ticket.

### Step 2: Describe your environment

  ```
  Issues submitted without sufficient information will be rejected.
  ```

  * Device: Thinkpad P52
  * OS version: Linux
  * Storefront pulled version: v3.0.12
  * Node version: v12.8.0
  * Docker version: 1.23.2
  * Docker Compose version: 19.03.2

### Step 3: Describe the problem:
Issue occurs when trying to adding a configurable item to a multi cart as a registered user. Not a problem as a public user as no multi carts.

#### Steps to reproduce:

  1. Log in as a registered user.
  2. Find a item that has a cart item modifier
  3. Fill in the fields for the cart item modifier.
  4. Add the item to cart. Pick the default cart if there is more than one option.

#### Observed Results:

  * What happened?  This could be a description, console log output, etc.

The item does not get added to the cart, and the add to cart button has the spinner run indefinitely.

Error:
```
Item <itemsku> is a configurable product. Please add it individually using 'additemtocart' form
```

#### Expected Results:

  * What did you expect to happen?
Expected to have the item added to the specified cart.

**Comment by shaunmaharaj** [comment]
Remove the check to prevent products with cart line item modifiers from being added to wishlists in #522.
I've created a support ticket to address the back-end bug for this. Will close this as the front-end piece related to this project is done and the back-end piece will be picked up via Zendesk.
