### ISSUE TITLE
Bulk Order and Quick Order forms do not notify the user when they succeed

### ISSUE THREAD

**Issue by plundaahl-ep** [elasticpath/react-pwa-reference-storefront#523]
### Step 1: Are you in the right place?

I think so.

### Step 2: Describe your environment

Observed on Reference Store hosted on AWS S3, compiled with Node version mentioned below.

  * Device: Macbook Pro (15-inc, 2018)
  * OS version: OSX Version 10.14.6 (18G103)
  * Storefront pulled version: v3.0.12 (commit `fc249c8`)
  * Node version: v11.15.0
  * Docker version: (irrelevant. Reference Store is statically-hosted)
  * Docker Compose version: (irrelevant. Reference Store is statically-hosted)

### Step 3: Describe the problem:

When logged in as a B2B user, the Bulk Order and Quick Order forms do not notify the user when they succeed. I believe is disconcerting for two reasons:

1) When adding to a cart from the Product Detail Page (as a B2B user) a notification pops up pointing at the mini cart. Not having this in the bulk order/quick order forms kind of leaves the user hanging, and also feels inconsistent (see screenshot).
![image](https://user-images.githubusercontent.com/54957521/70093318-f7a11300-15d4-11ea-9f90-a35ceafe66a2.png)

2) When a user enters erroneous data on either form, an error message pops up at the top of the screen. Users get feedback when they do something invalid, but not when they enter correct information.

In the Steps to Reproduce, I have covered demonstrating the behaviour for the Quick Order form. However, the same issue is present from the Bulk Order form, as well.

#### Steps to reproduce:

  1. Log in as a B2B user with Buyer privileges
  2. Click the lightning bolt icon
  3. Ensure you are on the "Quick Order" page
  4. Enter a valid SKU, but set the quantity to 1
  5. Click "Add All to Cart"
  6. Notice that an error is displayed
![image](https://user-images.githubusercontent.com/54957521/70093471-54043280-15d5-11ea-8c94-4420274513b2.png)
  7. Update the quantity to some positive number
  8. Click "Add All to Cart"

#### Observed Results:

  * The loading spinner runs
  * All fields are reset
  * The "Add All to Cart" is reset to disabled
  * No clear indicator of what happened (I am left thinking "did my items get put in the cart, or did the page just break and lose all my work?")

#### Expected Results:

  * Some sort of positive user feedback to be displayed (likely the same notification message used on the Product Detail pages). In particular, given that the Reference Store now supports multiple carts, it would likely be a good idea to give the user some feedback as to which cart their items were placed into.

**Comment by petro97** [comment]
@plundaahl-ep I'm trying to reproduce this issue but can not get this error:  'quantity' value must be greater than to equal to '1'.
Could you please check if this issue still exists?

**Comment by plundaahl-ep** [comment]
Hi @petro97,

Thanks for checking. I can't reproduce this either, so I'd assume it's been fixed (or perhaps something was up with my configuration).

Cheers!
