### ISSUE TITLE
Cannot remove the warning message banners during checkout flow

### ISSUE THREAD

**Issue by aChanEP** [elasticpath/react-pwa-reference-storefront#557]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For issues relating to EP-Commerce, or Cloud Ops in relation to the reference store please Open a Support ticket.

### Step 2: Describe your environment

  ```
  Issues submitted without sufficient information will be rejected.
  ```

  * Device: _____
  * OS version: _____
  * Storefront pulled version: _____
  * Node version: _____
  * Docker version: _____
  * Docker Compose version: _____

### Step 3: Describe the problem:

When going through the checkout flow the warning messages on the top of the page cannot be removed when pressing the `X`

#### Steps to reproduce:

  1. go through checkout flow
  2.notice messages appear from not having payment or address
  3. press X to remove

#### Observed Results:

  * They stay on the screen

#### Expected Results:

  * Should be removed from screen

#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by maennis-ep** [comment]
I think this is related to https://github.com/elasticpath/react-pwa-reference-storefront/issues/519

**Comment by aChanEP** [comment]
@maennis-ep yes seems like the same problem.  I'll close this issue.  Thanks
