### ISSUE TITLE
building production docker image fails

### ISSUE THREAD

**Issue by tenzing-danielm** [elasticpath/react-pwa-reference-storefront#71]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.

### Step 2: Describe your environment

  * Device: _N/A____
  * OS version: ___N/A__
  * Storefront pulled version: ___N/A__
  * Node version:  v8.12.0____

### Step 3: Describe the problem:

When attempting to build the docker image it's failing.

[dmulroo@danielm-m3 react-pwa-reference-storefront]$ pwd
/home/dmulroo/workspace/elastic/frontend/react-pwa-reference-storefront
[dmulroo@danielm-m3 react-pwa-reference-storefront]$ sudo docker build -t ep_build ./docker/prod/
Sending build context to Docker daemon 4.608 kB
Step 1/9 : FROM node:10.9.0 as builder
Error parsing reference: "node:10.9.0 as builder" is not a valid repository/tag: invalid reference format

#### Steps to reproduce:

  [dmulroo@danielm-m3 react-pwa-reference-storefront]$ pwd
/home/dmulroo/workspace/elastic/frontend/react-pwa-reference-storefront
[dmulroo@danielm-m3 react-pwa-reference-storefront]$ sudo docker build -t ep_build ./docker/prod/
Sending build context to Docker daemon 4.608 kB
Step 1/9 : FROM node:10.9.0 as builder
Error parsing reference: "node:10.9.0 as builder" is not a valid repository/tag: invalid reference format

#### Observed Results:

  * What happened?  This could be a description, console log output, etc.

#### Expected Results:

  * What did you expect to happen?

#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by shaunmaharaj** [comment]
Fixed the commands in the README as they were missing periods.
