### ISSUE TITLE
Prod docker image ngnix configuration is pointing to wrong root

### ISSUE THREAD

**Issue by tenzing-danielm** [elasticpath/react-pwa-reference-storefront#76]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.

### Step 2: Describe your environment

  * Device: _N/A____
  * OS version: _N/A____
  * Storefront pulled version: __N/A___
  * Node version: _N/A____
  * Docker version: ___N/A__
  * Docker Compose version: _N/A____

### Step 3: Describe the problem:

Deployed the prod docker container. When attempting to hit the site I'm getting the default ngnix index.html 

#### Steps to reproduce:

  1. __Build and deploy container___
  2. __Connect to URL on port 80, you get the default page___
  3. _____

#### Observed Results:

  wrong web site
#### Expected Results:

 should've got the reference store
#### Relevant Code:

listen       80;
    server_name  localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

I ended up connecting to the container and moving /usr/share/nginx/www to html and site is now up

**Comment by shaunmaharaj** [comment]
@asmurthwaite As discussed, the README needs to clarify the steps for building the production image. This is doc related.

**Comment by shaunmaharaj** [comment]
Documentation has been updated to clarify the steps for building the production image. Closing this one.
